### ISSUE TITLE
Data errors in categories, many errors

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#18]
For testing purposes data from original spreadsheet was imported, but it isn't all correct, e.g. categorisation of businesses is incorrect, and the 'Published' state of businesses is incorrect.

Page: /map
Focus: Business pop-up screen

Suggestion: Review data against original s/s

**Comment by joaquimds** [comment]
@ngm this conversation needs to move to YouTrack but could you provide an example of a Business where this bug is present, and what the correct properties (categories and state) should to be?

**Comment by ngm** [comment]
Manual clean up of data
