### ISSUE TITLE
Retain search criteria in the business list

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#29]
Search criteria is cleared when a business is selected for viewing.  This means that we need to reenter the search criteria each time if working through a group of related businesses, eg "draft" status, or "hackney".

Step to reproduce:
- go to list of businesses in admin section
- add a search term, e.g. 'draft'
- the list should now show businesses with draft status
- click on a particular business to see its business details page
- click back

Expected behaviour:
- list should still be filtered by 'draft'

Actual behaviour:
- search critiera is lost, we see all businesses

**Comment by ngm** [comment]
@NikhitaPaturu - I think this is now fixed, could you test please?  Thanks :)

**Comment by NikhitaPaturu** [comment]
Tested, it works fine.
