### ISSUE TITLE
Ability to share search results

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#56]
e.g. by including the search parameters on the query string.

**Comment by ngm** [comment]
e.g. by having the filters on the query string.

**Comment by ugomatic** [comment]
It'd be very useful to be able to share (and to link to) a specific business, rather than the full search.
Example use case: someone asks for a recommendation on twitter, or at a Restart Party, we could point them to a specific business when relevant.

**Comment by ngm** [comment]
No parameters are currently put on the query string.  I don't know if there was a good reason for this, related to the fact everything on the map is done via Javascript, or whether it just wasn't thought necessary at the time and would be easy to add in.  Will need to have a bit of a look into it.

**Comment by ngm** [comment]
Resolved with: https://github.com/TheRestartProject/RepairDirectory/pull/76
