### ISSUE TITLE
Search by category in London does not provide results

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/RepairDirectory#57]
I searched for "vacuum" under "London, UK" and no results. 

When in fact there is at least one entry for vacuums in the database.

**Comment by ngm** [comment]
Related to #55.

There is a Vacuum repair shop in Romford, so I'm guessing the search result coming from a search in London does not have a wide enough search radius to include it.

We could maybe increase the search radius, so a general 'London' search is big enough to include all results.

The problem would be that then a specific search, in e.g. Romford, would then include results from across all of London.  The results are currently ordered by positive reviews, so you would get badly ordered results.

Two thoughts:
* we could increase the radius and order results by proximity to entered address (not sure how difficult it is to do that OTOH)
* we could add an extra search parameter, which is 'search radius' (with a better name of course) that the user themselves can alter

thoughts @ugomatic ?

**Comment by ngm** [comment]
Noting that the current radius is 5 miles.

**Comment by ugomatic** [comment]
I think adding an extra search parameter is a good approach. Maybe something like 5/10/15+ miles, which could also allow for searching businesses beyond a specific town. 

In the backend we already have a field for city, so it should in theory be possible to have a city-wide option too. Other websites such as checkatrade give users the option to filter by "all of London"

**Comment by ngm** [comment]
> In the backend we already have a field for city, so it should in theory be possible to have a city-wide option too. 

We'd need to think of some way to flag that we want the search to use the city field rather than based on geocoding.

> Other websites such as checkatrade give users the option to filter by "all of London"
Could you link to that option @ugomatic , I can't see it e.g. here: https://www.checkatrade.com/Search/?location=se11+5su&cat=20

**Comment by ugomatic** [comment]
> Could you link to that option @ugomatic , I can't see it e.g. here: https://www.checkatrade.com/Search/?location=se11+5su&cat=20

it's not very intuitive: if you type "London" rather than a postcode, it'll give you the whole of London, however you can't them order them by proximity to you.

Related comment: perhaps we should consider improving "Where do you live?" suggesting using postcode or city are entered

**Comment by ngm** [comment]
Resolved for now by allowing 'All of London' in the search radius, which is just an 18 mile radius, large enough to cover all of London.

To be revisited with expansion to other cities, most likely making use of the City field as an optional search parameter.

c.f. https://github.com/TheRestartProject/RepairDirectory/pull/74
