### ISSUE TITLE
Default map location confusing

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/RepairDirectory#58]
Currently, it always default to "Romford", could it instead be "London", zoomed out for now?

Long-term, how do we take care of future cities? Access to location or other ways? (I like CityMapper's approach to "switching city", but might not be useful

**Comment by ngm** [comment]
For present we opted to centre on London by default, while the map is currently only in use in London.  

To be revisited upon expansion to other cities.

Resolved by: https://github.com/TheRestartProject/RepairDirectory/pull/75
