### ISSUE TITLE
How to allow multiple editors of the Directory?

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/RepairDirectory#61]
Currently, any backend user would be able to see/edit all records.

We need to come up with a way to allow:
- users to be associated with a city (or area?, or equivalent to the Restarter group on Fixometer?)

This is so that we reduce confusion and allow for curation/management of the directory by specific people in each geographic area

**Comment by ngm** [comment]
Just thinking out loud...

Whatever mechanism we choose, businesses would also need to be associated with that entity in some way.

The simplest from a development perspective is probably by groups, as we already have in the main Restarters module the factility to link users to groups, and it'd make sense to use that.  We'd need to then also have in the Repair Directory a way to associate businesses to the group.  It probably wouldn't work so great in for example London though, as if you'd be interested in businesses across London most likely, not just the ones maintained by a specific London group.

If it's by city or area, we could probably piggy back off the Town/City field we store on a user.  (If they choose to fill it in.)  This could perhaps then be associated with the town/city/area field (I forget what it is) in the Repair Directory against businesses.  It wouldn't really work as a 'permissions' thing, as anyone can change their town/city as they choose, but could work as a way of letting people only see businesses for editing that are in their vicinity.  This has problems in that the town/city in both the user-side and the business-side are freetext so there's no guarantee they will align.

There's the possible of showing businesses to a particular user based on geolocation.  Again assuming it's a convenience thing and not a permissions thing.  Reasonable geolocation depends on the user having entered both their town/city and country.  There's the constant problem of what radius to use if you're basing things on proximity, so it could be better to allow users to see all businesses as well as 'businesses near me'.

So I guess one question is whether we are concerned about permissions or simply convenience.  Are particular users going to be the final arbiter of what businesses appear in a particular geography or are we just looking for a way to make the management of businesses more convenient by showing those near you?
