### ISSUE TITLE
Better signposting when there's an error entering a record

### ISSUE THREAD

**Issue by ugomatic** [TheRestartProject/RepairDirectory#62]
When a business is saved with errors provide a pop-up banner (or other way) to highlight there is an error on the page. James says: "At present there is an error message against the relevant field, but it is easy to miss, and I have several times navigated away losing unsaved data."

**Comment by ngm** [comment]
In addition to this we could check for unsaved changes when navigating away from the page, and prompt whether you want to lose them or not.
