### ISSUE TITLE
Some partial London postcodes not recognised as London

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#84]
Some partial London postcodes not recognised as London.  Some are, some aren't, appears to be down to the whim of Google's geocoder.

e.g. SE16, NW1, E1 fine:

- https://map.restarters.net/?location=se16&category=&radius=18#
- https://map.restarters.net/?location=nw1&category=&radius=18#
- https://map.restarters.net/?location=e1&category=&radius=18#

e.g. N14, NE1 fails

- https://map.restarters.net/?location=n14&category=&radius=18#
- https://map.restarters.net/?location=ne1&category=&radius=18#

Full postcodes are fine.

I think a quick workaround could be to behind the scenes always append 'London, UK' to the geocoding query to Google (but obviously don't display this back to the user.)  Would need testing though that this doesn't cause the geocoder to trip up, e.g. how would it treat it if the user entered 'Hackney, London' and the query then became 'Hackney, London, London, UK'.  From what I've seen before the Google API is fairly good at dealing with redundancy in the address, but if not we'd have to add our own checks which would be a pain.

Obviously the above hardcodes it to London.  For expansion to cities elsewhere, we'd need an alternative method.  Off the top of my head, two possibilities would be:

- Citymapper style 'choose your city' before using the app
- append extra info to the geolocation based on the user's location as reported by the browser (bit intrusive doing this)

**Comment by ugomatic** [comment]
> I think a quick workaround could be to behind the scenes always append 'London, UK'
sounds good, it'd be great to do this in the short term if possible. I've just tested it with 'Hackney, London, London, UK', and it works no problem

> Citymapper style 'choose your city' before using the app
I think that would be the most elegant way of doing it - for each city we would need to give some info on which parts are covered (if not all)

**Comment by ngm** [comment]
Testing Google's geocoder here: https://developers.google.com/maps/documentation/geocoding/intro

Works OK for N14:

![image](https://user-images.githubusercontent.com/172324/49171479-89c56a00-f336-11e8-9ff4-6bdfc746a563.png)

Doesn't help for NE1:

![image](https://user-images.githubusercontent.com/172324/49171278-1c193e00-f336-11e8-8fdb-d7f6e9e3c9f9.png)

![image](https://user-images.githubusercontent.com/172324/49171330-33f0c200-f336-11e8-9134-162afbd2b4ff.png)

Playing with the order doesn't help two much:

![image](https://user-images.githubusercontent.com/172324/49171406-5d115280-f336-11e8-8e06-86667be1699c.png)

**Comment by ngm** [comment]
Noting it comes back as an array of results.  London is the second result.

![image](https://user-images.githubusercontent.com/172324/49171904-7ff03680-f337-11e8-8e32-e2a1687728d0.png)

We could possibly make use of the `postal_town` field to help pick out the correct result, but that is more work.

Anyway, short term we can add ", London, UK" in for those places where it does help.

**Comment by ngm** [comment]
This is live now.
