### ISSUE TITLE
Update to latest secure npm packages

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/RepairDirectory#87]
A couple of the packages have security vulnerabilities.

Just need to update to the latest versions - will be a good intro task for getting the build of the application up and running.

**Comment by spt1224** [comment]
For my own reference:
![image](https://user-images.githubusercontent.com/2263635/62570482-a7e85000-b85d-11e9-938e-eb5c1c502a31.png)

**Comment by spt1224** [comment]
Resolved. I will submit a PR once I've had the chance to test the app thoroughly.

![image](https://user-images.githubusercontent.com/2263635/62571639-d8c98480-b85f-11e9-88d8-5274d6a45754.png)
